package com.example.ind_05_maples_jordan

object State_Data {
    val stateList = listOf<State_Info>(
        State_Info("Alabama", "The Yellowhammer State", 52420),
        State_Info("Alaska", "The Last Frontier", 665384),
        State_Info("Arizona", "The Grand Canyon State", 113990),
        State_Info("Arkansas", "The Natural State", 53178),
        State_Info("California", "The Golden State", 163694),
        State_Info("Colorado", "The Centennial State", 104093),
        State_Info("Connecticut", "The Constitution State", 5543),
        State_Info("Delaware", "The First State", 2488),
        State_Info("Florida", "The Sunshine State", 65757),
        State_Info("Georgia", "The Peach State", 59425),
        State_Info("Hawaii", "The Aloha State", 10931),
        State_Info("Idaho", "The Gem State", 83568),
        State_Info("Illinois", "Land of Lincoln", 57913),
        State_Info("Indiana", "The Hoosier State", 36419),
        State_Info("Iowa", "The Hawkeye State", 56272),
        State_Info("Kansas", "The Sunflower State", 82278),
        State_Info("Kentucky", "The Bluegrass State", 40407),
        State_Info("Louisiana", "The Pelican State", 52378),
        State_Info("Maine", "The Pine Tree State", 35379),
        State_Info("Maryland", "The Old Line State", 12405),
        State_Info("Massachusetts", "The Bay State", 10554),
        State_Info("Michigan", "The Great Lakes State", 96713),
        State_Info("Minnesota", "The North Star State", 86935),
        State_Info("Mississippi", "The Magnolia State", 48431),
        State_Info("Missouri", "The Do Me State", 69706),
        State_Info("Montana", "The Treasure State", 147039),
        State_Info("Nebraska", "The Cornhusker State", 77347),
        State_Info("Nevada", "The Silver State", 110571),
        State_Info("New Hampshire", "The Granite State", 9349),
        State_Info("New Jersey", "The Garden State", 8722),
        State_Info("New Mexico", "The Land of Enchantment", 121590),
        State_Info("New York", "The Empire State", 54554),
        State_Info("North Carolina", "The Tar Heel State", 53819),
        State_Info("North Dakota", "The Peace Garden State", 70698),
        State_Info("Ohio", "The Buckeye State", 44825),
        State_Info("Oklahoma", "The Sooner State", 69898),
        State_Info("Oregon", "The Leave it to Beaver State", 98378),
        State_Info("Pennsylvania", "The Keystone State", 46054),
        State_Info("Rhode Island", "The Ocean's Twelve State", 1544),
        State_Info("South Carolina", "The Pimento Loaf State", 32020),
        State_Info("South Dakota", "Mount Shut YO Mouth State", 77115),
        State_Info("Tennessee", "The Guinea Pig State", 42144),
        State_Info("Texas", "The Lonely Island State", 268596),
        State_Info("Utah", "The Beeswax State", 84896),
        State_Info("Vermont", "The Green Mound State", 9616),
        State_Info("Virginia", "The Old Maid State", 42774),
        State_Info("Washington", "The Everclear State", 71297),
        State_Info("West Virginia", "The Mountain State", 24230),
        State_Info("Wisconsin", "The Wife-Badgering State", 65496),
        State_Info("Wyoming", "The Rainbow Flag State", 97813)
    )
}