package com.example.ind_05_maples_jordan

object State_Data {
    val stateList = listOf<State_Info>(
        State_Info("Alabama", "The Yellowhammer State", 52420, R.drawable.alabama, R.drawable.flagalabama),
        State_Info("Alaska", "The Last Frontier", 665384, R.drawable.alaska, R.drawable.flagalaska),
        State_Info("Arizona", "The Grand Canyon State", 113990, R.drawable.arizona, R.drawable.flagarizona),
        State_Info("Arkansas", "The Natural State", 53178, R.drawable.arkansas, R.drawable.flagarkansas),
        State_Info("California", "The Golden State", 163694, R.drawable.california,R.drawable.flagcalifornia),
        State_Info("Colorado", "The Centennial State", 104093, R.drawable.colorado, R.drawable.flagcolorado),
        State_Info("Connecticut", "The Constitution State", 5543, R.drawable.connecticut, R.drawable.flagconnecticut),
        State_Info("Delaware", "The First State", 2488, R.drawable.delaware, R.drawable.flagdelaware),
        State_Info("Florida", "The Sunshine State", 65757, R.drawable.florida, R.drawable.flagflorida),
        State_Info("Georgia", "The Peach State", 59425, R.drawable.georgia, R.drawable.flaggeorgia),
        State_Info("Hawaii", "The Aloha State", 10931, R.drawable.hawaii, R.drawable.flaghawaii),
        State_Info("Idaho", "The Gem State", 83568, R.drawable.idaho, R.drawable.flagidaho),
        State_Info("Illinois", "Land of Lincoln", 57913, R.drawable.illinois, R.drawable.flagillinois),
        State_Info("Indiana", "The Hoosier State", 36419, R.drawable.indiana, R.drawable.flagindiana),
        State_Info("Iowa", "The Swampass State", 56272, R.drawable.iowa, R.drawable.flagiowa),
        State_Info("Kansas", "The Sunflower State", 82278, R.drawable.kansas, R.drawable.flagkansas),
        State_Info("Kentucky", "The Bluegrass State", 40407, R.drawable.kentucky, R.drawable.flagkentucky),
        State_Info("Louisiana", "The Pelican State", 52378, R.drawable.louisiana, R.drawable.flaglouisiana),
        State_Info("Maine", "The Pine Tree State", 35379, R.drawable.maine, R.drawable.flagmaine),
        State_Info("Maryland", "The Old Line State", 12405, R.drawable.maryland,R.drawable.flagmaryland),
        State_Info("Massachusetts", "The Bay State", 10554, R.drawable.massachusetts, R.drawable.flagmassachusetts),
        State_Info("Michigan", "The Great Lakes State", 96713, R.drawable.michigan, R.drawable.flagmichigan),
        State_Info("Minnesota", "The North Star State", 86935, R.drawable.minnesota, R.drawable.flagminnesota),
        State_Info("Mississippi", "The Magnolia State", 48431, R.drawable.mississippi, R.drawable.flagmississippi),
        State_Info("Missouri", "The Do Me State", 69706, R.drawable.missouri, R.drawable.flagmissouri),
        State_Info("Montana", "The Treasure State", 147039, R.drawable.montana, R.drawable.flagmontana),
        State_Info("Nebraska", "The Cornhusker State", 77347, R.drawable.nebraska, R.drawable.flagnebraska),
        State_Info("Nevada", "The Silver State", 110571, R.drawable.nevada, R.drawable.flagnevada),
        State_Info("New Hampshire", "The Granite State", 9349, R.drawable.new_hampshire, R.drawable.flagnewhampshire),
        State_Info("New Jersey", "The Garden State", 8722, R.drawable.new_jersey, R.drawable.flagnewjersey),
        State_Info("New Mexico", "The Land of Enchantment", 121590, R.drawable.new_mexico, R.drawable.flagnewmexico),
        State_Info("New York", "The Empire State", 54554, R.drawable.new_york, R.drawable.flagnewyork),
        State_Info("North Carolina", "The Tar Heel State", 53819, R.drawable.north_carolina, R.drawable.flagnorthcarolina),
        State_Info("North Dakota", "The Peace Garden State", 70698, R.drawable.north_dakota, R.drawable.flagnorthdakota),
        State_Info("Ohio", "The Buckeye State", 44825, R.drawable.ohio, R.drawable.flagohio),
        State_Info("Oklahoma", "The Sooner State", 69898, R.drawable.oklahoma, R.drawable.flagoklahoma),
        State_Info("Oregon", "The Leave it to Beaver State", 98378, R.drawable.oregon, R.drawable.flagoregon),
        State_Info("Pennsylvania", "The Keystone State", 46054, R.drawable.pennsylvania, R.drawable.flagpennsylvania),
        State_Info("Rhode Island", "The Ocean's Twelve State", 1544, R.drawable.rhode_island, R.drawable.flagrhodeisland),
        State_Info("South Carolina", "The Pimento Loaf State", 32020, R.drawable.south_carolina, R.drawable.flagsouthcarolina),
        State_Info("South Dakota", "Mount Shut YO Mouth State", 77115, R.drawable.south_dakota, R.drawable.flagsouthdakota),
        State_Info("Tennessee", "The Guinea Pig State", 42144, R.drawable.tennessee, R.drawable.flagtennessee),
        State_Info("Texas", "The Lonely Island State", 268596, R.drawable.texas, R.drawable.flagtexas),
        State_Info("Utah", "The Beeswax State", 84896, R.drawable.utah, R.drawable.flagutah),
        State_Info("Vermont", "The Green Mound State", 9616, R.drawable.vermont, R.drawable.flagvermont),
        State_Info("Virginia", "The Old Maid State", 42774, R.drawable.virginia, R.drawable.flagvirginia),
        State_Info("Washington", "The Everclear State", 71297, R.drawable.washington, R.drawable.flagwashington),
        State_Info("West Virginia", "The Mountain State", 24230, R.drawable.west_virginia, R.drawable.flagwestvirginia),
        State_Info("Wisconsin", "The Wife-Badgering State", 65496, R.drawable.wisconsin, R.drawable.flagwisconsin),
        State_Info("Wyoming", "The Rainbow Flag State", 97813, R.drawable.wyoming, R.drawable.flagwyoming)
    )
}