package com.example.ind_05_maples_jordan

object State_Data {
    val stateList = listOf<State_Info>(
        State_Info("Alabama", "The Yellowhammer State", 52420, "alabama", "flagalabama"),
        State_Info("Alaska", "The Last Frontier", 665384, "alaska", "flagalaska"),
        State_Info("Arizona", "The Grand Canyon State", 113990, "arizona", "flagarizona"),
        State_Info("Arkansas", "The Natural State", 53178, "arkansas", "flagarkansas"),
        State_Info("California", "The Golden State", 163694, "california","flagcalifornia"),
        State_Info("Colorado", "The Centennial State", 104093, "colorado", "flagcolorado"),
        State_Info("Connecticut", "The Constitution State", 5543, "connecticut", "flagconnecticut"),
        State_Info("Delaware", "The First State", 2488, "delaware", "flagdelaware"),
        State_Info("Florida", "The Sunshine State", 65757, "florida", "flagflorida"),
        State_Info("Georgia", "The Peach State", 59425, "georgia", "flaggeorgia"),
        State_Info("Hawaii", "The Aloha State", 10931, "hawaii", "flaghawaii"),
        State_Info("Idaho", "The Gem State", 83568, "idaho", "flagidaho"),
        State_Info("Illinois", "Land of Lincoln", 57913, "illinois", "flagillinois"),
        State_Info("Indiana", "The Hoosier State", 36419, "indiana", "flagindiana"),
        State_Info("Iowa", "The Hawkeye State", 56272, "iowa", "flagiowa"),
        State_Info("Kansas", "The Sunflower State", 82278, "kansas", "flagkansas"),
        State_Info("Kentucky", "The Bluegrass State", 40407, "kentucky", "flagkentucky"),
        State_Info("Louisiana", "The Pelican State", 52378, "louisiana", "flaglouisiana"),
        State_Info("Maine", "The Pine Tree State", 35379, "maine", "flagmaine"),
        State_Info("Maryland", "The Old Line State", 12405, "maryland","flagmaryland"),
        State_Info("Massachusetts", "The Bay State", 10554, "massachusetts", "flagmassachusetts"),
        State_Info("Michigan", "The Great Lakes State", 96713, "michigan", "flagmichigan"),
        State_Info("Minnesota", "The North Star State", 86935, "minnesota", "flagminnesota"),
        State_Info("Mississippi", "The Magnolia State", 48431, "mississippi", "flagmississippi"),
        State_Info("Missouri", "The Do Me State", 69706, "missouri", "flagmissouri"),
        State_Info("Montana", "The Treasure State", 147039, "montana", "flagmontana"),
        State_Info("Nebraska", "The Cornhusker State", 77347, "nebraska", "flagnebraska"),
        State_Info("Nevada", "The Silver State", 110571, "nevada", "flagnevada"),
        State_Info("New Hampshire", "The Granite State", 9349, "newhampshire", "flagnewhampshire"),
        State_Info("New Jersey", "The Garden State", 8722, "newjersey","flagnewjersey"),
        State_Info("New Mexico", "The Land of Enchantment", 121590, "newmexico", "flagnewmexico"),
        State_Info("New York", "The Empire State", 54554, "newyork", "flagnewyork"),
        State_Info("North Carolina", "The Tar Heel State", 53819, "northcarolina", "flagnorthcarolina"),
        State_Info("North Dakota", "The Peace Garden State", 70698, "northdakota", "flagnorthdakota"),
        State_Info("Ohio", "The Buckeye State", 44825, "ohio", "flagohio"),
        State_Info("Oklahoma", "The Sooner State", 69898, "oklahoma", "flagoklahoma"),
        State_Info("Oregon", "The Leave it to Beaver State", 98378, "oregon", "flagoregon"),
        State_Info("Pennsylvania", "The Keystone State", 46054, "pennsylvania", "flagpennsylvania"),
        State_Info("Rhode Island", "The Ocean's Twelve State", 1544, "rhodeisland", "flagrhodeisland"),
        State_Info("South Carolina", "The Pimento Loaf State", 32020, "southcarolina", "flagsouthcarolina"),
        State_Info("South Dakota", "Mount Shut YO Mouth State", 77115, "southdakota", "flagsouthdakota"),
        State_Info("Tennessee", "The Guinea Pig State", 42144, "tennessee", "flagtennessee"),
        State_Info("Texas", "The Lonely Island State", 268596, "texas", "flagtexas"),
        State_Info("Utah", "The Beeswax State", 84896, "utah", "flagutah"),
        State_Info("Vermont", "The Green Mound State", 9616, "vermont", "flagvermont"),
        State_Info("Virginia", "The Old Maid State", 42774, "virginia", "flagvirginia"),
        State_Info("Washington", "The Everclear State", 71297, "washington", "flagwashington"),
        State_Info("West Virginia", "The Mountain State", 24230, "westvirginia", "flagwestvirginia"),
        State_Info("Wisconsin", "The Wife-Badgering State", 65496, "wisconsin", "flagwisconsin"),
        State_Info("Wyoming", "The Rainbow Flag State", 97813, "wyoming", "flagwyoming")
    )
}